plugins {
	alias libs.plugins.minotaur
	alias libs.plugins.shadow
}

apply from: '../gradle/loader.gradle'

architectury {
	platformSetupLoomIde()
	neoForge()
}

loom {
	neoForge {
		accessWidenerPath.set project(":common").file("src/main/resources/emcutils.accesswidener")
	}
}

configurations {
	developmentNeoForge.extendsFrom common
}

dependencies {
	neoForge libs.neoforge
}

processResources {
	inputs.property 'version', project.version

	filesMatching('META-INF/neoforge.mods.toml') {
		expand version: project.version
	}
}

jar {
	//atAccessWideners.add "emcutils.accesswidener"
}
